#!/bin/bash

#systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
#systemctl --user restart xdg-desktop-portal

#riverctl spawn "way-displays"
riverctl spawn "clstatus | dam"
riverctl spawn "swaybg -i ~/Imágenes/Wallpapers/samurai.jpg -m fill"
riverctl spawn "mako"
riverctl spawn "/usr/libexec/polkit-mate-authentication-agent-1"
riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY"
riverctl spawn "dbus-update-activation-environment --systemd XDG_CURRENT_DESKTOP=river"


riverctl default-layout rivercarro
rivercarro -outer-gaps 3 -per-tag &


riverctl map normal Super+Shift Return spawn "kitty"
riverctl map normal Super p spawn "wmenu-run -N 202020 -n d5c4a1 -S 504945 -s d5c4a1"
riverctl map normal Super+Shift C close
riverctl map normal Super+Shift Q exit


riverctl map normal Super Space toggle-float
riverctl map normal Super F toggle-fullscreen
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous
riverctl map normal Super Return zoom

riverctl map -repeat normal Super H send-layout-cmd rivercarro "main-ratio -0.01"
riverctl map -repeat normal Super L send-layout-cmd rivercarro "main-ratio +0.01"
riverctl map normal Super+Shift H send-layout-cmd rivercarro "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivercarro "main-count -1"
riverctl map normal Super Up send-layout-cmd rivercarro "main-location top"
riverctl map normal Super Right send-layout-cmd rivercarro "main-location right"
riverctl map normal Super Down send-layout-cmd rivercarro "main-location bottom"
riverctl map normal Super Left send-layout-cmd rivercarro "main-location left"
riverctl map normal Super M send-layout-cmd rivercarro "main-location monocle"
riverctl map normal Super W send-layout-cmd rivercarro "main-location-cycle left,monocle"

riverctl map -repeat normal Super+Alt H move left 1
riverctl map -repeat normal Super+Alt J move down 1
riverctl map -repeat normal Super+Alt K move up 1
riverctl map -repeat normal Super+Alt L move right 1
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right
riverctl map -repeat normal Super+Alt+Shift H resize horizontal -1
riverctl map -repeat normal Super+Alt+Shift J resize vertical 1
riverctl map -repeat normal Super+Alt+Shift K resize vertical -1
riverctl map -repeat normal Super+Alt+Shift L resize horizontal 1

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float


# Screenshot display and save to $HOME/Pictures
riverctl map normal none Print spawn "grim $HOME/Pictures/$(date +'%s.png')"
# Screenshot area and save to $HOME/Pictures
riverctl map normal Control Print spawn 'grim -g "$(slurp)" $HOME/Pictures/$(date +'%s.png')'

for i in $(seq 1 9)
do
	tags=$((1 << ($i - 1)))

	# Super+[1-9] to focus tag [0-8]
	riverctl map normal Super $i set-focused-tags $tags

	# Super+Shift+[1-9] to tag focused view with tag [0-8]
	riverctl map normal Super+Shift $i set-view-tags $tags

	# Super+Control+[1-9] to toggle focus of tag [0-8]
	riverctl map normal Super+Control $i toggle-focused-tags $tags

	# Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
	riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags; Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl set-repeat 75 300
riverctl focus-follows-cursor normal
riverctl set-cursor-warp normal
riverctl keyboard-layout -options caps:escape latam

riverctl border-color-focused 0x458588
riverctl border-color-unfocused 0xa89984ff
riverctl border-width 2
riverctl default-attach-mode bottom
riverctl xcursor-theme "phinger-cursors-dark"

#riverctl rule-add -app-id 'kitty' float
riverctl rule-add -app-id 'imv*' float
riverctl rule-add -app-id "bar" csd
riverctl rule-add -title 'Export Image*' -app-id 'gimp' float
riverctl rule-add -title 'Extension: *' -app-id 'librewolf' float
# riverctl rule-add -title '*Bitwarden*' -app-id 'librewolf' float


#scratch_tag=$((1 << 20 ))
#riverctl map normal Super P toggle-focused-tags ${scratch_tag}
#riverctl map normal Super+Shift P set-view-tags ${scratch_tag}
#all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
#riverctl spawn-tagmask ${all_but_scratch_tag}

riverctl declare-mode passthrough
riverctl map normal Super F11 enter-mode passthrough
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
	riverctl map -repeat $mode None XF86AudioRaiseVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+'
	riverctl map -repeat $mode None XF86AudioLowerVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'
	riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

	riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
	riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
	riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
	riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

	riverctl map -repeat $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
	riverctl map -repeat $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done
