[".emacs.d/init.el"]
    type = "file"
    url = "https://raw.githubusercontent.com/jamescherti/minimal-emacs.d/refs/heads/main/init.el"
    refreshPeriod = "168h"

[".emacs.d/early-init.el"]
    type = "file"
    url	= "https://raw.githubusercontent.com/jamescherti/minimal-emacs.d/refs/heads/main/early-init.el"
    refreshPeriod = "168h"

[".zsh/pure"]
    type = "git-repo"
    url = "https://github.com/sindresorhus/pure.git"
    refreshPeriod = "168h"

[".zsh/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"

[".zsh/zsh-syntax-hightlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"
